### ISSUE TITLE
Command '['update-ca-certificates']' returned non-zero exit status 1.

### ISSUE THREAD

**Issue by janusn** [Athozs/hass-additional-ca#14]
**Describe the issue**

Failed to load Additional CA integration.

**Describe your setup (please complete the following information):**

 - Installation type:  Docker
 - HAOS version (if applicable): 
 - Home Assistant core version:  2024.12.3
 - Additional CA integration version:  0.2.4
 - Kind of certificate you use:  self-signed CA certificate

**YAML configuration extract**

```yaml
default_config:

additional_ca:
  ng_ca: NG-CA.cert.pem
...
```

**Logs**

```
$ sudo docker logs homeassistant
...
2024-12-14 01:17:40.751 WARNING (MainThread) [custom_components.additional_ca.utils] 'update-ca-certificates' returned an error -> Command '['update-ca-certificates']' returned non-zero exit status 1.
2024-12-14 01:17:40.751 WARNING (MainThread) [custom_components.additional_ca] Additional CA setup has been interrupted.
2024-12-14 01:17:40.751 ERROR (MainThread) [homeassistant.setup] Error during setup of component additional_ca
Traceback (most recent call last):
  File "/usr/local/lib/python3.13/site-packages/homeassistant/setup.py", line 416, in _async_setup_component
    result = await task
             ^^^^^^^^^^
  File "/config/custom_components/additional_ca/__init__.py", line 44, in async_setup
    await update_ca_certificates(hass, config, store)
  File "/config/custom_components/additional_ca/__init__.py", line 88, in update_ca_certificates
    update_system_ca()
    ~~~~~~~~~~~~~~~~^^
  File "/config/custom_components/additional_ca/utils.py", line 53, in update_system_ca
    status = subprocess.run(cmd, capture_output=True, check=True)
  File "/usr/local/lib/python3.13/subprocess.py", line 577, in run
    raise CalledProcessError(retcode, process.args,
                             output=stdout, stderr=stderr)
subprocess.CalledProcessError: Command '['update-ca-certificates']' returned non-zero exit status 1.
...
```

Logs from Home Assistant WebUI
```
This error originated from a custom integration.

Logger: custom_components.additional_ca.utils
Source: custom_components/additional_ca/utils.py:55
integration: additional_ca (documentation, issues)
First occurred: 1:17:40 AM (1 occurrences)
Last logged: 1:17:40 AM

'update-ca-certificates' returned an error -> Command '['update-ca-certificates']' returned non-zero exit status 1.
```
```
This error originated from a custom integration.

Logger: custom_components.additional_ca
Source: custom_components/additional_ca/__init__.py:46
integration: additional_ca (documentation, issues)
First occurred: 1:17:40 AM (1 occurrences)
Last logged: 1:17:40 AM

Additional CA setup has been interrupted.
```
```
Logger: homeassistant.setup
Source: setup.py:416
First occurred: 1:17:40 AM (1 occurrences)
Last logged: 1:17:40 AM

Error during setup of component additional_ca
Traceback (most recent call last):
  File "/usr/local/lib/python3.13/site-packages/homeassistant/setup.py", line 416, in _async_setup_component
    result = await task
             ^^^^^^^^^^
  File "/config/custom_components/additional_ca/__init__.py", line 44, in async_setup
    await update_ca_certificates(hass, config, store)
  File "/config/custom_components/additional_ca/__init__.py", line 88, in update_ca_certificates
    update_system_ca()
    ~~~~~~~~~~~~~~~~^^
  File "/config/custom_components/additional_ca/utils.py", line 53, in update_system_ca
    status = subprocess.run(cmd, capture_output=True, check=True)
  File "/usr/local/lib/python3.13/subprocess.py", line 577, in run
    raise CalledProcessError(retcode, process.args,
                             output=stdout, stderr=stderr)
subprocess.CalledProcessError: Command '['update-ca-certificates']' returned non-zero exit status 1.
```

**Additional context**

 - What service/device are you trying to reach from Home Assistant with TLS/SSL ?

I am trying to connect to frigate with authentication on URI `https://10.19.33.53:8971`. It is newly supported by Frigate integration v5.6.0.

The folder structure inside docker:
```
# tree /config/
/config/
├── additional_ca
│   └── NG-CA.cert.pem
...
├── configuration.yaml
├── custom_components
│   ├── additional_ca
│   │   ├── __init__.py
│   │   ├── __pycache__
│   │   │   ├── __init__.cpython-313.pyc
│   │   │   ├── const.cpython-313.pyc
│   │   │   ├── storage.cpython-313.pyc
│   │   │   └── utils.cpython-313.pyc
│   │   ├── const.py
│   │   ├── manifest.json
│   │   ├── storage.py
│   │   └── utils.py
```

compose.yaml:
```
---
services:
  homeassistant:
    image: linuxserver/homeassistant:latest
    container_name: homeassistant
    deploy:
      resources:
        limits:
          memory: 2G
    network_mode: host
    environment:
      - PUID=1017
      - PGID=1017
      - TZ=Europe/London
      - REQUESTS_CA_BUNDLE=/etc/ssl/certs/ca-certificates.crt
    volumes:
      - "/etc/localtime:/etc/localtime:ro"
      - "./config:/config:rw"
      - "./cctv/ha/hass_events:/cctv:rw"
      - "./cctv/ha/nest:/config/nest:rw"
      - type: volume
        source: cctv
        target: /cctv
        volume:
          subpath: ha/hass_events
      - type: volume
        source: cctv
        target: /config/nest
        volume:
          subpath: ha/nest
    restart: unless-stopped
```

**Comment by janusn** [comment]
@Athozs 
Thanks a ton, mate!

**Comment by janusn** [comment]
Thanks for your reply.

I rather keep it running unprivileged. 

Thanks to your hard work, it inspires me on how to get it working. As I am using a linuxserver.io release, it allows me to run a custom procedure before the main task. I have followed your footsteps to update the ca certificates.
