### ISSUE TITLE
Detected blocking call (Part 2)

### ISSUE THREAD

**Issue by rwjack** [Athozs/hass-additional-ca#9]
**Describe the issue**

Hey, it seems that there might be one more piece of code that's triggering this warning.

```
Detected blocking call to listdir with args ('/usr/local/share/ca-certificates',) inside the event loop by custom integration 'additional_ca' at custom_components/additional_ca/utils.py, line 27: for filename in os.listdir(CA_SYSPATH): (offender: /config/custom_components/additional_ca/utils.py, line 27: for filename in os.listdir(CA_SYSPATH):), please create a bug report at https://github.com/Athozs/hass-additional-ca/issues For developers, please see https://developers.home-assistant.io/docs/asyncio_blocking_operations/#listdir Traceback (most recent call last): File "<frozen runpy>", line 198, in _run_module_as_main File "<frozen runpy>", line 88, in _run_code File "/usr/src/homeassistant/homeassistant/__main__.py", line 223, in <module> sys.exit(main()) File "/usr/src/homeassistant/homeassistant/__main__.py", line 209, in main exit_code = runner.run(runtime_conf) File "/usr/src/homeassistant/homeassistant/runner.py", line 190, in run return loop.run_until_complete(setup_and_run_hass(runtime_config)) File "/usr/local/lib/python3.12/asyncio/base_events.py", line 674, in run_until_complete self.run_forever() File "/usr/local/lib/python3.12/asyncio/base_events.py", line 641, in run_forever self._run_once() File "/usr/local/lib/python3.12/asyncio/base_events.py", line 1990, in _run_once handle._run() File "/usr/local/lib/python3.12/asyncio/events.py", line 88, in _run self._context.run(self._callback, *self._args) File "/usr/src/homeassistant/homeassistant/setup.py", line 167, in async_setup_component result = await _async_setup_component(hass, domain, config) File "/usr/src/homeassistant/homeassistant/setup.py", line 404, in _async_setup_component result = await task File "/config/custom_components/additional_ca/__init__.py", line 43, in async_setup await update_ca_certificates(hass, config, store) File "/config/custom_components/additional_ca/__init__.py", line 81, in update_ca_certificates remove_all_additional_ca(additional_ca_data) File "/config/custom_components/additional_ca/utils.py", line 27, in remove_all_additional_ca for filename in os.listdir(CA_SYSPATH): 
```

**Describe your setup (please complete the following information):**

 - Installation type:  HAOS 
Core 2024.7.1
Supervisor 2024.06.2
Operating System 12.4 
 - Additional CA integration version: 0.2.3 
 - Kind of certificate you use: Self-signed

**Comment by rwjack** [comment]
@Athozs I'm not seeing the warning anymore. Bless your soul and have a wonderful weekend.
